# -*- coding: utf-8 -*-
"""EF_MachineLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPIvLZLFGnL0dlIplKQ-zeyu8BfGhhyx
"""

# BLOQUE 1: Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Configuración visual
sns.set(style="whitegrid")
print("Librerías cargadas correctamente.")

# BLOQUE 2: Carga y Transformación Inicial
# Cargar datos
filename = "precios-inmobiliarios-bd-desagregada-venta-2025-2.xlsx"
df = pd.read_excel(filename)

# Renombrar columnas para estandarización
mapa_columnas = {
    'Precio en dólares corrientes': 'Precio',
    'Superficie ': 'Area_m2', # Ojo con el espacio original
    'Número de habitaciones': 'Habitaciones',
    'Número de baños': 'Banos',
    'Número de garajes': 'Garajes',
    'Años de antigüedad': 'Antiguedad',
    'Distrito': 'Distrito',
    'Tipo de cambio': 'TC_Venta',
    'IPC': 'IPC',
    'Año': 'Anio'
}
df = df.rename(columns=mapa_columnas)

# Filtrar alcance del proyecto (2010 - 2025)
df = df[(df['Anio'] >= 2010) & (df['Anio'] <= 2025)]

# EVIDENCIA 1 PARA TU INFORME (Captura esto)
print("--- Primeras 5 filas del Dataset Integrado ---")
print(df[['Anio', 'Distrito', 'Area_m2', 'Precio', 'TC_Venta', 'IPC']].head())

# BLOQUE 3: Limpieza de Nulos y Outliers (IQR)

# 1. Eliminar nulos críticos
df_clean = df.dropna(subset=['Precio', 'Area_m2', 'Habitaciones', 'Banos', 'Distrito'])
df_clean['Antiguedad'] = df_clean['Antiguedad'].fillna(df_clean['Antiguedad'].median())

# 2. Algoritmo IQR (Tal cual tu informe)
def filtrar_outliers(data, col):
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return data[(data[col] >= lower) & (data[col] <= upper)]

# Aplicamos filtro al Precio
df_final = filtrar_outliers(df_clean, 'Precio')

# Gráfico para Evidencia (Opcional pero recomendado)
plt.figure(figsize=(10, 4))
sns.boxplot(x=df_final['Precio'])
plt.title("Distribución de Precios post-limpieza (Sin Outliers)")
plt.show()

# EVIDENCIA 2 (Datos resultantes)
print(f"Registros originales: {len(df)}")
print(f"Registros tras limpieza: {len(df_final)}")

# BLOQUE 4: Ingeniería de Características

# Definir X (Predictoras) e y (Objetivo)
features = ['Area_m2', 'Habitaciones', 'Banos', 'Antiguedad', 'Distrito', 'TC_Venta', 'IPC']
X = df_final[features]
y = df_final['Precio']

# Transformador de columnas
# Numéricas -> StandardScaler
# Categóricas (Distrito) -> OneHotEncoder
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Area_m2', 'Habitaciones', 'Banos', 'Antiguedad', 'TC_Venta', 'IPC']),
        ('cat', OneHotEncoder(handle_unknown='ignore'), ['Distrito'])
    ])

# División Train/Test (80% / 20%) [cite: 180]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Datos divididos correctamente.")
print(f"Entrenamiento: {X_train.shape[0]} datos")
print(f"Prueba: {X_test.shape[0]} datos")

# BLOQUE 5: Entrenamiento y Evaluación Comparativa

# Diccionario de modelos
modelos = {
    "Regresión Lineal": LinearRegression(),
    "Árbol de Decisión": DecisionTreeRegressor(random_state=42, max_depth=10), # Limitamos profundidad para evitar overfit
    "K-Nearest Neighbors": KNeighborsRegressor(n_neighbors=7)
}

resultados = []

for nombre, modelo in modelos.items():
    # Crear Pipeline
    pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                               ('model', modelo)])

    # Entrenar
    pipeline.fit(X_train, y_train)

    # Predecir
    y_pred = pipeline.predict(X_test)

    # Métricas
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    resultados.append([nombre, mae, rmse, r2])

# Crear Tabla de Resultados
df_resultados = pd.DataFrame(resultados, columns=["Modelo", "MAE (Error Absoluto)", "RMSE (Raíz Error Cuadrático)", "R2 (Precisión)"])

# EVIDENCIA FINAL (Tabla Comparativa)
print("--- COMPARACIÓN DE RENDIMIENTO ---")
print(df_resultados)

# Implementación del Algoritmo de Árbol de Decisión para Predicción
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np # Asegúrate de que numpy esté importado para np.sqrt

# Configuración del modelo con profundidad controlada para evitar overfitting
modelo_arbol = DecisionTreeRegressor(max_depth=10, random_state=42)

# Aplicar el preprocesamiento a los datos de entrenamiento y prueba
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# Entrenamiento del modelo con datos históricos (80%)
modelo_arbol.fit(X_train_processed, y_train)

# Generación de predicciones sobre el conjunto de prueba (20%)
y_pred_arbol = modelo_arbol.predict(X_test_processed)

# Evaluación de métricas
r2 = r2_score(y_test, y_pred_arbol)
mse = mean_squared_error(y_test, y_pred_arbol)
rmse = np.sqrt(mse) # Calcular RMSE manualmente

print(f"Precisión del Modelo (R2): {r2:.4f}")
print(f"Raíz del Error Cuadrático Medio (RMSE): {rmse:.4f}")

import pandas as pd
from IPython.display import display

# 1. Definimos escenarios hipotéticos (Casas que queremos tasar)
# Asumimos valores futuros o actuales para simular
nuevos_datos_raw = pd.DataFrame({
    'Area_m2': [60, 80, 100, 120, 150],       # Tamaños variados
    'Habitaciones': [2, 3, 3, 4, 4],          # Habitaciones
    'Banos': [1, 2, 2, 3, 3],                 # Baños
    'Antiguedad': [5, 10, 0, 15, 2],          # Años de antigüedad (ejemplo)
    'Distrito': ['San Miguel', 'Miraflores', 'San Isidro', 'Santiago de Surco', 'La Molina'], # Nombres de distritos
    'TC_Venta': [3.75, 3.75, 3.80, 3.80, 3.85], # Proyección de Tipo de Cambio futuro
    'IPC': [1.5, 1.5, 1.6, 1.6, 1.7]          # Proyección de IPC futuro
})

# 2. Preprocesar los nuevos datos usando el mismo preprocessor
# El preprocessor fue definido en BLOQUE 4
nuevos_datos_processed = preprocessor.transform(nuevos_datos_raw)

# 3. Usamos el MEJOR modelo para predecir (modelo_arbol en este caso)
predicciones_futuras = modelo_arbol.predict(nuevos_datos_processed)

# 4. Creamos la tabla de resultados visual
resultados_finales = nuevos_datos_raw.copy() # Usamos los datos crudos para la visualización
resultados_finales['Precio_Predicho_USD'] = predicciones_futuras.round(2)
resultados_finales['Escenario'] = ['Pequeño-Económico', 'Mediano-Estándar', 'Familiar', 'Residencial', 'Premium-Futuro']

# Mostrar la tabla
import seaborn as sns
cm = sns.light_palette("green", as_cmap=True)
display(resultados_finales.style.background_gradient(cmap=cm, subset=['Precio_Predicho_USD']))

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# BLOQUE 6: Generación de Gráfico de Proyecciones (2025-2030)

# 1. Definir el "Inmueble Tipo" para la simulación
# Usaremos la moda (lo más común) para que sea representativo
distrito_top = df_final['Distrito'].mode()[0]
area_prom = df_final[df_final['Distrito'] == distrito_top]['Area_m2'].median()
habs_prom = df_final[df_final['Distrito'] == distrito_top]['Habitaciones'].median()
banos_prom = df_final[df_final['Distrito'] == distrito_top]['Banos'].median()

print(f"--- Simulación para Inmueble en {distrito_top} ({area_prom} m2) ---")

# 2. Proyectar Macroeconomía (TC e IPC) usando tendencia lineal simple
# Tomamos los datos históricos para calcular la tendencia anual
datos_hist = df_final.groupby('Anio')[['TC_Venta', 'IPC']].mean().reset_index()

# Ajuste polinómico de grado 1 (Línea recta)
z_tc = np.polyfit(datos_hist['Anio'], datos_hist['TC_Venta'], 1)
z_ipc = np.polyfit(datos_hist['Anio'], datos_hist['IPC'], 1)
proyeccion_tc = np.poly1d(z_tc)
proyeccion_ipc = np.poly1d(z_ipc)

# 3. Crear DataFrame de Futuro (2025 - 2030)
anios_futuros = np.arange(2025, 2031)
data_futura = []

for anio in anios_futuros:
    data_futura.append({
        'Area_m2': area_prom,
        'Habitaciones': habs_prom,
        'Banos': banos_prom,
        'Antiguedad': 5, # Asumimos una antigüedad fija promedio
        'Distrito': distrito_top,
        'TC_Venta': proyeccion_tc(anio),
        'IPC': proyeccion_ipc(anio)
    })

df_futuro = pd.DataFrame(data_futura)

# 4. Predecir con los 3 modelos ya entrenados
# (Asegúrate de que 'modelos' contiene tus 3 pipelines entrenados del paso anterior)
predicciones = {'Año': anios_futuros}

# Re-entrenamos pipelines completos si no están guardados en variables accesibles
# (Esto es seguridad por si se borró la memoria del Colab)
from sklearn.pipeline import Pipeline
for nombre, modelo_base in [('Regresión Lineal', LinearRegression()),
                            ('Árbol de Decisión', DecisionTreeRegressor(max_depth=10, random_state=42)),
                            ('KNN', KNeighborsRegressor(n_neighbors=7))]:

    pipe = Pipeline(steps=[('preprocessor', preprocessor), ('model', modelo_base)])
    pipe.fit(X_train, y_train) # Entrenamos
    predicciones[nombre] = pipe.predict(df_futuro) # Predecimos

df_proyeccion = pd.DataFrame(predicciones)

# 5. Graficar Resultados
plt.figure(figsize=(12, 6))

# Estilos de línea para diferenciar
estilos = {'Regresión Lineal': 'dashed', 'Árbol de Decisión': 'solid', 'KNN': 'dotted'}
colores = {'Regresión Lineal': 'red', 'Árbol de Decisión': 'green', 'KNN': 'blue'}

for modelo in ['Regresión Lineal', 'Árbol de Decisión', 'KNN']:
    plt.plot(df_proyeccion['Año'], df_proyeccion[modelo],
             marker='o', label=modelo, linestyle=estilos[modelo], color=colores[modelo], linewidth=2)

plt.title(f'Proyección de Valor de Mercado (2025-2030)\nDistrito: {distrito_top} | Área: {area_prom}m²', fontsize=16)
plt.xlabel('Año de Proyección', fontsize=12)
plt.ylabel('Precio Estimado (USD)', fontsize=12)
plt.legend(title="Algoritmo de IA")
plt.grid(True, which='both', linestyle='--', alpha=0.7)
plt.xticks(anios_futuros) # Asegurar que salgan todos los años

# Mostrar y Guardar
plt.tight_layout()
plt.show()

# Imprimir tabla numérica para anexo
print("\n--- TABLA DE DATOS PROYECTADOS (USD) ---")
print(df_proyeccion)

# IMPLEMENTACIÓN DEL MODELO GANADOR: K-NEAREST NEIGHBORS (KNN)
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline

# Configuración del Pipeline Óptimo
# 1. Preprocesamiento: Escalado de variables (Crítico para KNN)
# 2. Modelo: KNN con 7 vecinos (k=7) definido experimentalmente
modelo_final = Pipeline(steps=[
    ('preprocessor', preprocessor), # Tu transformador de datos definido antes
    ('knn', KNeighborsRegressor(n_neighbors=7, metric='euclidean'))
])

# Entrenamiento con el set completo de datos
modelo_final.fit(X_train, y_train)

# Validación de métricas
print(f"Precisión Final (R2): {modelo_final.score(X_test, y_test):.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# --- BLOQUE GRÁFICO ESPECÍFICO PARA KNN ---

# Asegúrate de tener 'modelo_final' (tu Pipeline KNN) ya entrenado
# Si no, corre el bloque de entrenamiento del "Ganador" que te di antes.

# 1. GRÁFICO DE PRECISIÓN: REAL VS PREDICHO
# Este gráfico demuestra la potencia del R2 de 0.79
y_pred_knn = modelo_final.predict(X_test)

plt.figure(figsize=(14, 6))

# Subplot 1: Real vs Predicho
plt.subplot(1, 2, 1)
sns.scatterplot(x=y_test, y=y_pred_knn, alpha=0.5, color='blue', edgecolor='k')
# Línea de perfección (Donde debería estar si fuera 100% perfecto)
max_val = max(y_test.max(), y_pred_knn.max())
min_val = min(y_test.min(), y_pred_knn.min())
plt.plot([min_val, max_val], [min_val, max_val], 'r--', lw=2, label='Predicción Perfecta')

plt.title(f'Precisión del Modelo KNN (R² = {modelo_final.score(X_test, y_test):.2f})', fontsize=12)
plt.xlabel('Precio Real (USD)', fontsize=10)
plt.ylabel('Precio Predicho por KNN (USD)', fontsize=10)
plt.legend()
plt.grid(True, alpha=0.3)

# 2. GRÁFICO DE COMPORTAMIENTO: LA "FORMA" DEL KNN
# Vamos a aislar un Distrito para ver cómo "piensa" el KNN
plt.subplot(1, 2, 2)

# Elegimos un distrito representativo y filtramos datos reales
distrito_demo = 'Miraflores' # O el distrito que prefieras
datos_distrito = df[df['Distrito'] == distrito_demo]

# Graficamos los puntos reales de ese distrito
sns.scatterplot(data=datos_distrito, x='Area_m2', y='Precio',
                alpha=0.4, color='gray', label='Datos Reales')

# Simulamos predicción KNN solo variando el Área (Ceteris Paribus)
# Mantenemos fijas las otras variables en su promedio
areas_simuladas = np.linspace(datos_distrito['Area_m2'].min(), datos_distrito['Area_m2'].max(), 100)
datos_simulados = pd.DataFrame({
    'Area_m2': areas_simuladas,
    'Habitaciones': [datos_distrito['Habitaciones'].median()] * 100,
    'Banos': [datos_distrito['Banos'].median()] * 100,
    'Antiguedad': [datos_distrito['Antiguedad'].median()] * 100,
    'Distrito': [distrito_demo] * 100,
    'TC_Venta': [df['TC_Venta'].mean()] * 100,
    'IPC': [df['IPC'].mean()] * 100
})

# Predecimos la curva
linea_knn = modelo_final.predict(datos_simulados)

# Pintamos la línea del KNN
plt.plot(areas_simuladas, linea_knn, color='red', lw=3, label='Curva de Ajuste KNN')

plt.title(f'Comportamiento No Lineal del KNN en {distrito_demo}', fontsize=12)
plt.xlabel('Área (m²)', fontsize=10)
plt.ylabel('Precio Estimado (USD)', fontsize=10)
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

from sklearn.inspection import permutation_importance

# Calculamos la importancia (puede tardar unos segundos)
results = permutation_importance(modelo_final, X_test, y_test, n_repeats=10, random_state=42)

# Ordenamos los resultados
sorted_idx = results.importances_mean.argsort()

plt.figure(figsize=(10, 6))
plt.barh(range(len(sorted_idx)), results.importances_mean[sorted_idx], color='teal')
plt.yticks(range(len(sorted_idx)), [X_test.columns[i] for i in sorted_idx])
plt.xlabel("Disminución de la Precisión (Importancia)")
plt.title("¿Qué variables definen más el precio según el modelo?")
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

residuos = y_test - y_pred_knn

plt.figure(figsize=(10, 6))
sns.histplot(residuos, kde=True, color='purple', bins=30)
plt.axvline(x=0, color='red', linestyle='--', linewidth=2, label='Error Cero (Ideal)')
plt.title('Distribución de los Errores de Predicción')
plt.xlabel('Error en Dólares (Real - Predicho)')
plt.ylabel('Frecuencia (Cantidad de Casas)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# Dato extra para el texto:
print(f"La mayoría de los errores oscilan entre: ${np.percentile(residuos, 25):.0f} y ${np.percentile(residuos, 75):.0f}")

# Creamos 3 casos de prueba manuales
casos_prueba = pd.DataFrame({
    'Area_m2': [60, 120, 250],            # Pequeño, Mediano, Grande
    'Habitaciones': [2, 3, 5],
    'Banos': [1, 2, 4],
    'Antiguedad': [5, 10, 2],             # Nuevo, Usado, Lujo
    'Distrito': ['Los Olivos', 'Jesus Maria', 'San Isidro'], # Periferia, Medio, Top
    'TC_Venta': [3.75, 3.75, 3.75],       # Tipo de cambio actual
    'IPC': [df['IPC'].iloc[-1], df['IPC'].iloc[-1], df['IPC'].iloc[-1]] # IPC actual
})

predicciones = modelo_final.predict(casos_prueba)

# Mostramos resultados bonitos
for i, precio in enumerate(predicciones):
    print(f"Caso {i+1} ({casos_prueba.iloc[i]['Distrito']}, {casos_prueba.iloc[i]['Area_m2']}m2): ${precio:,.2f}")

# BLOQUE CORREGIDO PARA GRAFICAR IMPORTANCIA (OPTIMIZADO)
from sklearn.inspection import permutation_importance
import matplotlib.pyplot as plt

# 1. TRUCO: Usamos solo una muestra de 500 datos para que no se cuelgue
# Esto es estadísticamente válido para interpretar el modelo
X_test_sample = X_test.sample(n=500, random_state=42)
y_test_sample = y_test.loc[X_test_sample.index]

print("Calculando importancia de variables (versión optimizada)...")

# 2. Ejecutamos con menos repeticiones (5 es suficiente)
results = permutation_importance(modelo_final, X_test_sample, y_test_sample,
                               n_repeats=5, random_state=42, n_jobs=-1)

# 3. Ordenamos los resultados
sorted_idx = results.importances_mean.argsort()

# 4. Graficamos
plt.figure(figsize=(10, 6))
plt.barh(range(len(sorted_idx)), results.importances_mean[sorted_idx], color='teal')
plt.yticks(range(len(sorted_idx)), [X_test.columns[i] for i in sorted_idx])
plt.xlabel("Impacto en el Precio (Importancia)")
plt.title("¿Qué variables definen más el precio? (Análisis KNN)")
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()